In [1]:
import tensorflow

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
#Vocabulary size
voc_size = 10000

**One Hot Representation**

In [6]:
onehot_repre = [one_hot(words, voc_size) for words in sent]
print(onehot_repre)

[[4542, 8507, 7660, 383], [4542, 8507, 7660, 6482], [4542, 73, 7660, 5270], [8183, 1499, 1140, 593, 7177], [8183, 1499, 1140, 593, 8665], [8390, 4542, 2741, 7660, 7036], [6306, 5198, 1890, 593]]


**Word Embedding Represntation**

In [19]:
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [21]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repre,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4542 8507 7660  383]
 [   0    0    0    0 4542 8507 7660 6482]
 [   0    0    0    0 4542   73 7660 5270]
 [   0    0    0 8183 1499 1140  593 7177]
 [   0    0    0 8183 1499 1140  593 8665]
 [   0    0    0 8390 4542 2741 7660 7036]
 [   0    0    0    0 6306 5198 1890  593]]


In [22]:
dim =10

In [23]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, 10))
model.compile('adam', 'mse')

In [24]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step
[[[ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896
   -0.03050594 -0.01764716 -0.02969871 -0.04176639 -0.02972629]
  [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896
   -0.03050594 -0.01764716 -0.02969871 -0.04176639 -0.02972629]
  [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896
   -0.03050594 -0.01764716 -0.02969871 -0.04176639 -0.02972629]
  [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896
   -0.03050594 -0.01764716 -0.02969871 -0.04176639 -0.02972629]
  [ 0.03740906 -0.01140261  0.03858722 -0.02267455  0.01047946
   -0.00376914 -0.02613814  0.01484669 -0.0343362   0.04921002]
  [ 0.0346556  -0.04966122  0.00379932  0.02761105  0.03362573
    0.00960994  0.00888635  0.03083868  0.02258888 -0.0371327 ]
  [ 0.03955517  0.01740856 -0.02590548 -0.02410153  0.04810587
    0.01749165 -0.00818761  0.00813364  0.02423408  0.03398461]
  [-0.0441769  -0.02130564 -0.03831252 -0.01841838  0.02347617
    0.032

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 4542, 8507, 7660,  383])

In [29]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896 -0.03050594
  -0.01764716 -0.02969871 -0.04176639 -0.02972629]
 [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896 -0.03050594
  -0.01764716 -0.02969871 -0.04176639 -0.02972629]
 [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896 -0.03050594
  -0.01764716 -0.02969871 -0.04176639 -0.02972629]
 [ 0.03322932  0.02428669 -0.04553203  0.02660838 -0.00228896 -0.03050594
  -0.01764716 -0.02969871 -0.04176639 -0.02972629]
 [ 0.03740906 -0.01140261  0.03858722 -0.02267455  0.01047946 -0.00376914
  -0.02613814  0.01484669 -0.0343362   0.04921002]
 [ 0.0346556  -0.04966122  0.00379932  0.02761105  0.03362573  0.00960994
   0.00888635  0.03083868  0.02258888 -0.0371327 ]
 [ 0.03955517  0.01740856 -0.02590548 -0.02410153  0.04810587  0.01749165
  -0.00818761  0.00813364  0.02423408  0.03398461]
 [-0.0441769  -0.02130564 -0.03831252 -0.01841838  0.02347617  0.03280437
   0.04679438